AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Globals:
  Function:
    Runtime: nodejs6.10
    Timeout: 15
    MemorySize: 256
    AutoPublishAlias: live
    DeploymentPreference:
      Type: Canary10Percent5Minutes

Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: ./
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: GET
