name: test

on: 
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    environment: Dev Branch 1
    steps:
      - name: echo
        env:
          WEBSITE_APPPOOL: ${{ vars.WEBSITE_APPPOOL }}
          WEBSITE_NAME: ${{ vars.WEBSITE_NAME }}
          WEBSITE_PARENTSITE: ${{ vars.WEBSITE_PARENTSITE }}
        run: |
          echo "Website AppPool: $WEBSITE_APPPOOL"
          echo "Website Name: $WEBSITE_NAME"
          echo "Parent Site: $WEBSITE_PARENTSITE"
      
