name: test

on: 
  workflow_dispatch:
    inputs:
      channel:
        description: 'Deploy Target Channel'
        required: true
        type: choice
        options:
          - "Dev Branch 1"
          - "Dev Branch 2"
          - "Dev Branch 3"
          - "Dev Branch 4" 
jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.channel }}
    env:
      WEBSITE_APPPOOL: ${{ vars.WEBSITE_APPPOOL }}
      WEBSITE_NAME: ${{ vars.WEBSITE_NAME }}
      WEBSITE_PARENTSITE: ${{ vars.WEBSITE_PARENTSITE }}
      WEBSITE_BINDING: ${{ vars.WEBSITE_BINDING }}
    steps:
      - name: echo
        run: |
          echo "Website AppPool: $WEBSITE_APPPOOL"
          echo "Website Name: $WEBSITE_NAME"
          echo "Parent Site: $WEBSITE_PARENTSITE"
          echo "Website Binding: $WEBSITE_BINDING"
      
